### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by arshishir** [JuliaDiffEq/DiffEqFlux.jl#89] opened 2019-11-21 02:26 UTC
I just downloaded Julia Pro, which comes with Julia 1.0.5. I added DifferentialEquations, Flux, LinearAlgebra, Plots, and DiffEqFlux. 

> julia> Pkg.status()
>     Status `~/.juliapro/JuliaPro_v1.0.5-2/environments/v1.0/Project.toml`
>   [c52e3926] Atom v0.11.2
>   [aae7a2af] DiffEqFlux v0.8.0 [`~/.juliapro/JuliaPro_v1.0.5-2/dev/DiffEqFlux`]
>   [0c46a032] DifferentialEquations v6.8.0
>   [587475ba] Flux v0.9.0
>   [7073ff75] IJulia v1.20.0
>   [e5e0dc1b] Juno v0.7.2
>   [91a5bcdd] Plots v0.27.0
>   [37e2e46d] LinearAlgebra 

However when I do: using DiffEqFlux, I get:

> Info: Precompiling DiffEqFlux [aae7a2af-3d4f-5e19-a356-7da93b79d9d0]
> ERROR: LoadError: LoadError: syntax: invalid function name "Morris <: GSAMethod"
> Stacktrace:
>  [1] include at ./boot.jl:317 [inlined]
>  [2] include_relative(::Module, ::String) at ./loading.jl:1044
>  [3] include at ./sysimg.jl:29 [inlined]
>  [4] include(::String) at /Users/lukesh/.juliapro/JuliaPro_v1.0.5-2/packages/DiffEqSensitivity/aR25O/src/DiffEqSensitivity.jl:3
>  [5] top-level scope at none:0
>  [6] include_relative(::Module, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [7] include(::Module, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [8] top-level scope at none:2
>  [9] eval at ./boot.jl:319 [inlined]
>  [10] eval(::Expr) at ./client.jl:393
>  [11] top-level scope at ./none:3
> in expression starting at /Users/lukesh/.juliapro/JuliaPro_v1.0.5-2/packages/DiffEqSensitivity/aR25O/src/morris_sensitivity.jl:1
> in expression starting at /Users/lukesh/.juliapro/JuliaPro_v1.0.5-2/packages/DiffEqSensitivity/aR25O/src/DiffEqSensitivity.jl:17
> ERROR: LoadError: Failed to precompile DiffEqSensitivity [41bf760c-e81c-5289-8e54-58b1f1f8abe2] to /Users/lukesh/.juliapro/JuliaPro_v1.0.5-2/compiled/v1.0/DiffEqSensitivity/02xYn.ji.
> Stacktrace:
>  [1] error(::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [2] compilecache(::Base.PkgId, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [3] _require(::Base.PkgId) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [4] require(::Base.PkgId) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:? (repeats 2 times)
>  [5] include_relative(::Module, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [6] include(::Module, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [7] top-level scope at none:2
>  [8] eval at ./boot.jl:319 [inlined]
>  [9] eval(::Expr) at ./client.jl:393
>  [10] top-level scope at ./none:3
> in expression starting at /Users/lukesh/.juliapro/JuliaPro_v1.0.5-2/dev/DiffEqFlux/src/DiffEqFlux.jl:3
> ERROR: Failed to precompile DiffEqFlux [aae7a2af-3d4f-5e19-a356-7da93b79d9d0] to /Users/lukesh/.juliapro/JuliaPro_v1.0.5-2/compiled/v1.0/DiffEqFlux/BdO4p.ji.
> Stacktrace:
>  [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
>  [2] _require(::Base.PkgId) at ./loading.jl:960
>  [3] require(::Base.PkgId) at ./loading.jl:858
>  [4] require(::Module, ::Symbol) at ./loading.jl:853

**Comment by ChrisRackauckas** [comment] 2019-11-21 04:58
Duplicate of https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/81 . I would recommend using the latest Julia release (1.2) to avoid this issue.

**Closed by ChrisRackauckas** 2019-11-21 04:58 UTC

**Comment by arshishir** [comment] 2019-11-21 05:12
That's what I figured out too. Thank you @ChrisRackauckas
