### ISSUE TITLE
BoundsError when taking gradient

### ISSUE THREAD

**Issue by jessebett** [JuliaDiffEq/DiffEqFlux.jl#35] opened 2019-04-05 17:49 UTC
```
using Flux, DiffEqFlux, OrdinaryDiffEq,  StatsBase, RecursiveArrayTools
using Flux: onehotbatch
using MLDatasets:MNIST
using Base.Iterators: repeated,partition

batch_size=10

train_x, train_y = MNIST.traindata();
test_x, test_y = MNIST.testdata();
train_y_hot = onehotbatch(train_y,0:9);

train_data = [(reshape(train_x[:,:,i],(28,28,1,batch_size)),train_y_hot[:,i]) for i in partition(1:60_000,batch_size)];

downsample = Chain(
                   Conv((3,3),1=>32,stride=1),
                   BatchNorm(32,relu),
                   Conv((4,4),32=>32,stride=2,pad=1),
                   BatchNorm(32,relu),
                   Conv((4,4),32=>32,stride=2,pad=1)
                  )
dudt = Chain(
          BatchNorm(32,relu),
          Conv((3,3),32=>32,stride =1, pad=1),
          BatchNorm(32),
          Conv((3,3),32=>32,stride =1, pad=1),
          BatchNorm(32)
          )
classify = Chain(
                 BatchNorm(32,relu), 
                 MeanPool((6,6)),
                 x->view(x,1,1,:,:), #Need More General Flatten Here
                 Dense(32,10)
                )

ps = Flux.params(dudt)

function n_ode(batch_u0, batch_t)
    neural_ode(dudt,batch_u0,(0.,25.),Tsit5(),
               save_start=false,
               saveat=batch_t,      # Ugly way to only get sol[end] 
               reltol=1e-3,abstol=1e-3)
end

model = Chain(downsample,u->n_ode(u,[25.])[:,:,:,:,end],classify) # Further ugliness getting sol[end]

loss(x,y) = Flux.mse(model(x),y)

loss(train_data[1]...) # Works and is tracked
# This fails with neural_ode_rd with T undefined error

opt = ADAM(0.1)
Ps = params(model,ps)

Tracker.gradient(()->loss(xt,yt),Ps) # Fails with BoundsError
#ERROR: BoundsError: attempt to access 6×6×32×10×1 Array{Float32,5} at index [Base.Slice(Base.OneTo(6)), 1]

Flux.train!(loss, Ps, train_data, opt, cb = ()) # Fails with BoundsError
```

The loss produces a tracked scalar, but taking gradients causes a BoundsError. 

Further, if I use `neural_ode_rd` instead it doesn't even evaluate the forward pass correctly, as there's a `T undefined` error.

**Comment by jessebett** [comment] 2019-04-05 19:21
I believe this is related to #19 and how batched dimensions are accessed, which was closed but not fixed.

Using that example

```
using Flux, DiffEqFlux, OrdinaryDiffEq, StatsBase, RecursiveArrayTools
using Distributions

const tspan = (0.0f0,25f0)
const RANGE = (Float32(-8.),Float32(8.))
const BS = 200

target(u) = u.^3

function gen_data(batchsize,target_fun)
    x = Float32.(rand(Uniform(RANGE...,),batchsize))'|>collect
    return x,target(x)
end

dudt = Chain(Dense(1,20,tanh),Dense(20,20,tanh),Dense(20,1))
function n_ode(u0)
    neural_ode(dudt,u0,tspan,Tsit5(),
               #= save_start=false, =#
               #= save_everystep=false, =#
               #= save_on=false, =#
               reltol=1e-5,abstol=1e-12)
end
ps = Flux.params(dudt)

loss(x,y) = mean(abs.(n_ode(x)[:,:,end]-y))

data = Iterators.repeated(gen_data(BS,target), 10000) 
opt = ADAM(0.01)
cb = function () #callback function to observe training
    tx,ty = gen_data(BS,target)
    display(loss(tx,ty))
end

# Display the ODE with the initial parameter values.
cb()

Flux.train!(loss, ps, data, opt, cb = cb) 
```

The handling of the solution is extremely brittle, can easily break reverse pass, and I'm unable to get gradients returned:

If I don't use any soln handling arguments to `neural_ode` then the returned value of `n_ode` has all the time steps from the solver. Not great. But I tried to handle this solution by taking `[:,:,end]` in the loss. However, this breaks the gradient pass with BoundsError:

```
dudt = Chain(Dense(1,20,tanh),Dense(20,20,tanh),Dense(20,1))
function n_ode(u0)
    neural_ode(dudt,u0,tspan,Tsit5(),
               #= save_start=false, =#
               #= save_everystep=false, =#
               #= save_on=false, =#
               reltol=1e-5,abstol=1e-12)
end
ps = Flux.params(dudt)

# Solution has all solver timesteps Tracked 1×200×24 Array{Float32,3}
n_ode(u0_test) 

# Handle extra time steps in loss, a natural thing to think to do...
loss(x,y) = mean(abs.(n_ode(x)[:,:,end]-y)) 

# This breaks gradient pass with BoundsError
# ERROR: BoundsError: attempt to access 1×200×24 Array{Float32,3} at index [Base.Slice(Base.OneTo(1)), 24]
Tracker.gradient(()->loss(u0_test,y0_test),ps)
```

So I tried to handle the saved time steps internally, which is desired for memory reasons anyway. 
Some of these options are redundant, 
```
dudt = Chain(Dense(1,20,tanh),Dense(20,20,tanh),Dense(20,1))
function n_ode(u0)
    neural_ode(dudt,u0,tspan,Tsit5(),
               save_start=false,
               save_on=false,
               reltol=1e-5,abstol=1e-12)
end
ps = Flux.params(dudt)

# This produces a solution with only one saved time corresponding to sol[end]
n_ode(u0_test) # Tracked 1×200×1 Array{Float32,3}:

# And gradients can be taken without BoundsError:
Tracker.gradient(()->loss(u0_test,y0_test),ps)

# However, these gradients contain no information
[print(g) for g in Tracker.gradient(()->loss(u0_test,y0_test),ps)] # zeros
```

**Comment by ChrisRackauckas** [comment] 2019-04-06 21:41
In the first example, `xt,yt` are both undefined.

**Comment by taliesinb** [comment] 2019-04-07 08:51
The `T undefined` error comes from a missing automatic conversion between float32 and float64 for tracked arrays (I cannot now find the original thread where I saw this, sorry). To force a 32-bit solution you'll need to make the `tspan` tuple float32.

**Comment by jessebett** [comment] 2019-04-08 18:11
@ChrisRackauckas sorry I wasn't careful in restarting a new REPL when putting up the issue code. `xt, yt = train_data[1]`

**Comment by ChrisRackauckas** [comment] 2019-04-09 11:09
Yes, with those fixes this becomes the batching issue. I'm going to close this as a duplicate of https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/19

**Closed by ChrisRackauckas** 2019-04-09 11:09 UTC
